# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-04 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='image',
            field=models.ImageField(upload_to='child_selfie'),
        ),
    ]
