# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-05 02:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0004_relative'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.RemoveField(
            model_name='relative',
            name='relatedTo',
        ),
        migrations.AddField(
            model_name='relative',
            name='relatedTo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='children.Child'),
            preserve_default=False,
        ),
    ]
