# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-05 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0006_auto_20161105_0307'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='children',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='home',
            name='director',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='home',
            name='organization',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='home',
            name='social_worker',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='home',
            name='staff_in_charge',
            field=models.CharField(default='', max_length=20),
        ),
    ]
