# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-05 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0007_auto_20161105_0329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='children',
        ),
        migrations.AddField(
            model_name='home',
            name='children',
            field=models.ManyToManyField(to='children.Child'),
        ),
    ]
