# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-05 03:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0008_auto_20161105_0330'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='parent_home',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='children.Home'),
        ),
    ]
